### ISSUE TITLE
Empty status field on HTTPProxy objects fails CRD validation

### ISSUE THREAD

**Issue by youngnick** [projectcontour/ir2proxy#41]
From @moderation:

The empty status: {} stanza at the end of a converted IngressRoute object causes the following deployment failures in our environment:
```
error: error validating "kube\\kustomize\\overlays\\local": error validating data: [ValidationError(HTTPProxy.status): missing required field "currentStatus" in io.projectcontour.v1.HTTPProxy.status, ValidationError(HTTPProxy.status): missing required field "description" in io.projectcontour.v1.HTTPProxy.status]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by youngnick** [comment]
This should be fixed by ensuring that the HTTPProxy CRD from Contour is up to date. As part of the creation of this tool, we changed the `currentstatus` and `description` fields to optional.

You should be able to apply these straight from github if you want with:
```
kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/v1.2.0/examples/contour/01-crds.yaml
```
Or you can download the YAML and check it before applying as well.

The CRD should apply cleanly over the top of the old one.

**Comment by youngnick** [comment]
Over you to @moderation.

**Comment by moderation** [comment]
I can see the change to not requiring status for 1.0.0 to 1.0.1 at https://github.com/projectcontour/contour/commit/768510af6486f20ed032f20515a9878db07c16b0#diff-f675f5d75aa05398c331aface6ef3e0c. We had to downgrade to 1.0.0 due to various issues and hence why we are hitting this - I'll make sure we follow the updated CRDs as we upgrade.

Does it make sense to omit an empty `status: {}` stanza on each conversion considering the field is no longer required? I'm thinking of converting this tool to a web tool that will allow developers to paste their old IngressRoute YAML into a text box and get the HTTPProxy conversion.

**Comment by youngnick** [comment]
Sadly, because of API guarantees, I couldn't change the HTTPProxy definition to allow the empty `status: {}` stanza to be left out. So, the `status` field itself is required, but the fields under it are not. Which means that, unfortunately, `status: {}` is required. I hope to address this if and when we do a HTTPProxy v2.

A web tool sounds really neat! If you want to use this tools packages as a library for a web service, please log issues as required - new issues are preferable to commenting on old issues, as we don't get notified for updates on closed issues.

**Comment by youngnick** [comment]
Closing this one out as I believe it's done now.
